from pathlib import Path
p=Path('Sources/RGSibilanceStudio.swift')
s=p.read_text()
s=s.replace('let RGVersion = "0.2.21"','let RGVersion = "0.2.22"')
s=s.replace('struct SibilanceEvent {','struct SibilanceEvent: Codable {')
insert='''\nstruct FileSession: Codable {\n    var path: String\n    var fileSize: UInt64\n    var modificationTime: Double\n    var duration: Double\n    var sampleRate: Double\n    var events: [SibilanceEvent]\n    var typeTrims: [String: Double]\n}\n\nfinal class SessionStore {\n    private let fm = FileManager.default\n\n    private var directory: URL {\n        let base = fm.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support/RG Sibilance Studio/Sessions", isDirectory: true)\n        try? fm.createDirectory(at: base, withIntermediateDirectories: true)\n        return base\n    }\n\n    private func stableHash(_ text: String) -> String {\n        var hash: UInt64 = 1469598103934665603\n        for b in text.utf8 { hash = (hash ^ UInt64(b)) &* 1099511628211 }\n        return String(format: "%016llx", hash)\n    }\n\n    private func sessionURL(for url: URL) -> URL {\n        directory.appendingPathComponent(stableHash(url.standardizedFileURL.path) + ".json")\n    }\n\n    private func signature(_ url: URL) -> (UInt64, Double)? {\n        guard let attrs = try? fm.attributesOfItem(atPath: url.path),\n              let size = attrs[.size] as? NSNumber,\n              let date = attrs[.modificationDate] as? Date else { return nil }\n        return (size.uint64Value, date.timeIntervalSince1970)\n    }\n\n    func load(for url: URL, duration: Double, sampleRate: Double) -> FileSession? {\n        guard let sig = signature(url),\n              let data = try? Data(contentsOf: sessionURL(for: url)),\n              let session = try? JSONDecoder().decode(FileSession.self, from: data) else { return nil }\n        guard session.path == url.standardizedFileURL.path,\n              session.fileSize == sig.0,\n              abs(session.modificationTime - sig.1) < 0.001,\n              abs(session.duration - duration) < 0.001,\n              abs(session.sampleRate - sampleRate) < 0.5 else { return nil }\n        return session\n    }\n\n    func save(for url: URL, duration: Double, sampleRate: Double, events: [SibilanceEvent], typeTrims: [String: Double]) {\n        guard let sig = signature(url) else { return }\n        let session = FileSession(path: url.standardizedFileURL.path, fileSize: sig.0, modificationTime: sig.1, duration: duration, sampleRate: sampleRate, events: events, typeTrims: typeTrims)\n        guard let data = try? JSONEncoder().encode(session) else { return }\n        try? data.write(to: sessionURL(for: url), options: .atomic)\n    }\n}\n'''
s=s.replace('\nfinal class AudioModel {',insert+'\nfinal class AudioModel {',1)
# timeline callbacks/state
s=s.replace('    var onEventFadesChanged: ((Int, Double, Double) -> Void)?','    var onEventFadesChanged: ((Int, Double, Double) -> Void)?\n    var onCreateEventRegion: ((Double, Double) -> Void)?')
s=s.replace('    private var fadeDragSide: Int = 0','    private var fadeDragSide: Int = 0\n    private var selectingRegion = false\n    private var selectionAnchor: Double?\n    private var selectionCurrent: Double?')
# mouseDown selection before other actions after plot guard
needle='''        guard plotRect.contains(p) else { return }\n\n        if let i = eventIndexAtBadge(p) {'''
repl='''        guard plotRect.contains(p) else { return }\n\n        if event.modifierFlags.contains(.shift) {\n            selectingRegion = true\n            let t = timeForX(p.x)\n            selectionAnchor = t\n            selectionCurrent = t\n            playhead = t\n            highlightedTime = t\n            needsDisplay = true\n            return\n        }\n\n        if let i = eventIndexAtBadge(p) {'''
s=s.replace(needle,repl,1)
# mouseDragged selection first
needle='''        let p = convert(event.locationInWindow, from: nil)\n        if let i = gainDragIndex, events.indices.contains(i) {'''
repl='''        let p = convert(event.locationInWindow, from: nil)\n        if selectingRegion {\n            let t = timeForX(min(max(p.x, plotRect.minX), plotRect.maxX))\n            selectionCurrent = t\n            playhead = t\n            highlightedTime = t\n            needsDisplay = true\n        } else if let i = gainDragIndex, events.indices.contains(i) {'''
s=s.replace(needle,repl,1)
# mouseUp selection callback
needle='''    override func mouseUp(with event: NSEvent) {\n        if scrubbing { onScrub?(playhead, false) }'''
repl='''    override func mouseUp(with event: NSEvent) {\n        if selectingRegion, let a = selectionAnchor, let b = selectionCurrent {\n            let start = min(a, b)\n            let end = max(a, b)\n            selectingRegion = false\n            selectionAnchor = nil\n            selectionCurrent = nil\n            if end - start >= 0.015 { onCreateEventRegion?(start, end) }\n        }\n        if scrubbing { onScrub?(playhead, false) }'''
s=s.replace(needle,repl,1)
# draw selection between waveform and events
s=s.replace('''        drawWaveform(m)\n        drawEvents(m)''','''        drawWaveform(m)\n        drawSelectionRegion()\n        drawEvents(m)''',1)
# add drawSelection function before drawEvents
needle='''    private func drawEvents(_ m: AudioModel) {'''
func='''    private func drawSelectionRegion() {\n        guard let a = selectionAnchor, let b = selectionCurrent else { return }\n        let x1 = xForTime(min(a, b))\n        let x2 = xForTime(max(a, b))\n        let r = NSRect(x: min(x1, x2), y: plotRect.minY, width: max(2, abs(x2 - x1)), height: plotRect.height)\n        NSColor.systemCyan.withAlphaComponent(0.16).setFill()\n        r.fill()\n        NSColor.systemCyan.withAlphaComponent(0.9).setStroke()\n        let border = NSBezierPath(rect: r)\n        border.lineWidth = 1.5\n        border.stroke()\n        let attrs: [NSAttributedString.Key: Any] = [.font: NSFont.boldSystemFont(ofSize: 10), .foregroundColor: NSColor.white]\n        "NEW EVENT REGION".draw(at: NSPoint(x: r.minX + 6, y: r.maxY - 18), withAttributes: attrs)\n    }\n\n'''
s=s.replace(needle,func+needle,1)
s=s.replace('"Scroll: zoom   •   center fader: event gain   •   fade dots: crossfade length   •   region edges: START/END   •   Space: play/stop"','"Scroll: zoom   •   ⇧ drag: select new event region   •   center fader: gain   •   fade dots: crossfade   •   Space: play/stop"')
# App session store
s=s.replace('    private let updater = UpdateManager()','    private let updater = UpdateManager()\n    private let sessionStore = SessionStore()')
# timeline callback
s=s.replace('''        timeline.onEventFadesChanged = { [weak self] i, fadeIn, fadeOut in self?.eventFadesChanged(i, fadeIn: fadeIn, fadeOut: fadeOut) }''','''        timeline.onEventFadesChanged = { [weak self] i, fadeIn, fadeOut in self?.eventFadesChanged(i, fadeIn: fadeIn, fadeOut: fadeOut) }\n        timeline.onCreateEventRegion = { [weak self] start, end in self?.createEventFromSelection(start: start, end: end) }''')
# load restore
old='''                    self.eventInfo.stringValue = "Audio loaded — analyzing automatically…"\n                    self.status.stringValue = "AUDIO LOADED — starting automatic analysis…"\n                    self.analyzeAudio()'''
new='''                    if let session = self.sessionStore.load(for: url, duration: m.duration, sampleRate: m.sampleRate) {\n                        self.events = session.events\n                        self.typeTrims = session.typeTrims\n                        self.timeline.events = session.events\n                        self.timeline.selectedIndex = session.events.isEmpty ? nil : 0\n                        self.detectedLabel.stringValue = "Restored: \\(session.events.count) events"\n                        self.eventInfo.stringValue = session.events.isEmpty ? "Saved session restored" : "Saved session restored — last stage"\n                        if !session.events.isEmpty { self.selectEvent(0) }\n                        self.status.stringValue = "SESSION RESTORED — unchanged audio file"\n                    } else {\n                        self.eventInfo.stringValue = "Audio loaded — analyzing automatically…"\n                        self.status.stringValue = "AUDIO LOADED — starting automatic analysis…"\n                        self.analyzeAudio()\n                    }'''
s=s.replace(old,new,1)
# helper autosave before sensitivityChanged
needle='''    @objc private func sensitivityChanged() {'''
helpers='''    private func saveCurrentSession() {\n        guard let url = model.url else { return }\n        sessionStore.save(for: url, duration: model.duration, sampleRate: model.sampleRate, events: events, typeTrims: typeTrims)\n    }\n\n    private func createEventFromSelection(start: Double, end: Double) {\n        guard end - start >= 0.015 else { return }\n        let menu = NSMenu()\n        for kind in ["S", "Š", "Z", "C", "Č", "T", "Ť", "D", "K", "P", "B", "F", "CH", "OTHER"] {\n            let item = NSMenuItem(title: kind, action: #selector(createSelectedRegionEvent(_:)), keyEquivalent: "")\n            item.target = self\n            item.representedObject = ["start": start, "end": end, "kind": kind] as [String : Any]\n            menu.addItem(item)\n        }\n        let p = NSEvent.mouseLocation\n        if let screen = NSScreen.main {\n            let local = NSPoint(x: p.x - screen.frame.minX, y: p.y - screen.frame.minY)\n            menu.popUp(positioning: nil, at: local, in: nil)\n        } else {\n            menu.popUp(positioning: nil, at: NSPoint(x: 200, y: 200), in: nil)\n        }\n    }\n\n    @objc private func createSelectedRegionEvent(_ sender: NSMenuItem) {\n        guard let d = sender.representedObject as? [String: Any],\n              let start = d["start"] as? Double, let end = d["end"] as? Double, let kind = d["kind"] as? String else { return }\n        let e = SibilanceEvent(start: start, end: end, peakTime: (start + end) * 0.5, score: 1, kind: kind, userLabel: "TARGET")\n        events.append(e)\n        events.sort { $0.peakTime < $1.peakTime }\n        timeline.events = events\n        detectedLabel.stringValue = "Detected: \\(events.count) events"\n        if let i = events.firstIndex(where: { abs($0.start - start) < 0.000001 && abs($0.end - end) < 0.000001 && $0.kind == kind }) {\n            selectEvent(i)\n            timeline.playhead = events[i].start\n        }\n        saveCurrentSession()\n        status.stringValue = "NEW [\\(kind)] EVENT — \\(String(format: \"%.3f\", start))–\\(String(format: \"%.3f\", end)) s"\n    }\n\n'''
s=s.replace(needle,helpers+needle,1)
# autosave at mutation points/status unique strings
repls=[
('self.status.stringValue = found.isEmpty ? "ANALYSIS COMPLETE — no events" : "ANALYSIS COMPLETE"','self.saveCurrentSession()\n                self.status.stringValue = found.isEmpty ? "ANALYSIS COMPLETE — no events" : "ANALYSIS COMPLETE"'),
('status.stringValue = String(format: "EVENT #%d REGION → %.3f–%.3f s", i + 1, start, end)','saveCurrentSession()\n        status.stringValue = String(format: "EVENT #%d REGION → %.3f–%.3f s", i + 1, start, end)'),
('status.stringValue = String(format: "EVENT #%d CROSSFADES — IN %.0f ms / OUT %.0f ms", i + 1, events[i].fadeIn * 1000, events[i].fadeOut * 1000)','saveCurrentSession()\n        status.stringValue = String(format: "EVENT #%d CROSSFADES — IN %.0f ms / OUT %.0f ms", i + 1, events[i].fadeIn * 1000, events[i].fadeOut * 1000)'),
('status.stringValue = String(format: "EVENT #%d GAIN %.1f dB", i + 1, events[i].gainDB)','saveCurrentSession()\n        status.stringValue = String(format: "EVENT #%d GAIN %.1f dB", i + 1, events[i].gainDB)'),
('status.stringValue = String(format: "EVENT #%d CROSSFADES — IN %.0f ms / OUT %.0f ms", i + 1, fadeIn * 1000, fadeOut * 1000)','saveCurrentSession()\n        status.stringValue = String(format: "EVENT #%d CROSSFADES — IN %.0f ms / OUT %.0f ms", i + 1, fadeIn * 1000, fadeOut * 1000)'),
('status.stringValue = String(format: "%@ TYPE TRIM %.1f dB — %d events", kind, value, count)','saveCurrentSession()\n        status.stringValue = String(format: "%@ TYPE TRIM %.1f dB — %d events", kind, value, count)'),
('status.stringValue = "EVENT #\\(i + 1) TYPE → \\(title)"','saveCurrentSession()\n        status.stringValue = "EVENT #\\(i + 1) TYPE → \\(title)"'),
('status.stringValue = "EVENT #\\(i + 1) MARKED \\(value)"','saveCurrentSession()\n        status.stringValue = "EVENT #\\(i + 1) MARKED \\(value)"'),
('status.stringValue = "MANUAL SIBILANCE ADDED"','saveCurrentSession()\n        status.stringValue = "MANUAL SIBILANCE ADDED"'),
('status.stringValue = "SIBILANCE REMOVED"','saveCurrentSession()\n        status.stringValue = "SIBILANCE REMOVED"')]
for a,b in repls:
    s=s.replace(a,b,1)
p.write_text(s)
