from pathlib import Path

path = Path('Sources/RGSibilanceStudio.swift')
s = path.read_text()

replacements = [
    ('let RGVersion = "0.2.19"', 'let RGVersion = "0.2.20"'),
    ('    var userLabel: String\n}', '    var userLabel: String\n    var gainDB: Double = 0\n    var fadeIn: Double = 0.012\n    var fadeOut: Double = 0.012\n}'),
    ('    var onEventBoundsChanged: ((Int, Double, Double) -> Void)?\n', '    var onEventBoundsChanged: ((Int, Double, Double) -> Void)?\n    var onPlayEvent: ((Int) -> Void)?\n    var onEventGainChanged: ((Int, Double) -> Void)?\n'),
    ('    private var boundaryDrag: Int = 0\n', '    private var boundaryDrag: Int = 0\n    private var gainDragIndex: Int?\n'),
    ('        guard plotRect.contains(p) else { return }\n\n        if let i = selectedIndex, events.indices.contains(i) {', '''        guard plotRect.contains(p) else { return }\n\n        if let i = eventIndexAtBadge(p) {\n            selectedIndex = i\n            onSelect?(i)\n            playhead = events[i].start\n            highlightedTime = events[i].start\n            onPlayEvent?(i)\n            needsDisplay = true\n            return\n        }\n\n        if let i = selectedIndex, events.indices.contains(i), gainFaderRect(for: i).contains(p) {\n            gainDragIndex = i\n            updateGainDrag(i, x: p.x)\n            return\n        }\n\n        if let i = selectedIndex, events.indices.contains(i) {'''),
    ('        if boundaryDrag != 0, let i = selectedIndex, events.indices.contains(i), let m = model {', '''        if let i = gainDragIndex, events.indices.contains(i) {\n            updateGainDrag(i, x: p.x)\n        } else if boundaryDrag != 0, let i = selectedIndex, events.indices.contains(i), let m = model {'''),
    ('        boundaryDrag = 0\n        needsDisplay = true\n', '        boundaryDrag = 0\n        gainDragIndex = nil\n        needsDisplay = true\n'),
    ('    func followPlayback(to time: Double) {', '''    private func eventIndexAtBadge(_ point: NSPoint) -> Int? {\n        for (i, e) in events.enumerated() where e.end >= viewStart && e.start <= viewEnd {\n            let centerX = xForTime(e.peakTime)\n            let selected = i == selectedIndex\n            let width: CGFloat = selected ? 48 : 30\n            let height: CGFloat = selected ? 28 : 20\n            let rect = NSRect(x: centerX - width / 2, y: plotRect.maxY - height - 4, width: width, height: height)\n            if rect.contains(point) { return i }\n        }\n        return nil\n    }\n\n    private func gainFaderRect(for i: Int) -> NSRect {\n        guard events.indices.contains(i) else { return .zero }\n        let centerX = xForTime(events[i].peakTime)\n        return NSRect(x: centerX - 34, y: plotRect.maxY - 57, width: 68, height: 18)\n    }\n\n    private func updateGainDrag(_ i: Int, x: CGFloat) {\n        guard events.indices.contains(i) else { return }\n        let rect = gainFaderRect(for: i)\n        let fraction = min(1, max(0, (x - rect.minX) / max(1, rect.width)))\n        let value = -12.0 + Double(fraction) * 12.0\n        events[i].gainDB = value\n        onEventGainChanged?(i, value)\n        needsDisplay = true\n    }\n\n    func followPlayback(to time: Double) {'''),
    ('            badgeText.draw(at: NSPoint(x: centerX - textSize.width / 2, y: badgeY + (badgeH - textSize.height) / 2), withAttributes: attrs)\n', '''            badgeText.draw(at: NSPoint(x: centerX - textSize.width / 2, y: badgeY + (badgeH - textSize.height) / 2), withAttributes: attrs)\n\n            if selected {\n                let fader = gainFaderRect(for: i)\n                let lineY = fader.midY\n                let line = NSBezierPath()\n                line.move(to: NSPoint(x: fader.minX + 4, y: lineY))\n                line.line(to: NSPoint(x: fader.maxX - 4, y: lineY))\n                NSColor.white.withAlphaComponent(0.32).setStroke()\n                line.lineWidth = 2\n                line.stroke()\n                let norm = CGFloat((min(0, max(-12, e.gainDB)) + 12) / 12)\n                let knobX = fader.minX + 4 + norm * (fader.width - 8)\n                let knob = NSBezierPath(ovalIn: NSRect(x: knobX - 5, y: lineY - 5, width: 10, height: 10))\n                NSColor.white.setFill()\n                knob.fill()\n                let gattrs: [NSAttributedString.Key: Any] = [.font: NSFont.monospacedDigitSystemFont(ofSize: 8, weight: .semibold), .foregroundColor: NSColor.white.withAlphaComponent(0.85)]\n                String(format: "%.1f dB", e.gainDB).draw(at: NSPoint(x: fader.maxX + 4, y: fader.minY + 3), withAttributes: gattrs)\n            }\n'''),
    ('    private var stopMode: NSSegmentedControl!\n', '    private var stopMode: NSSegmentedControl!\n    private var fadeInSlider: NSSlider!\n    private var fadeOutSlider: NSSlider!\n    private var fadeInValue: NSTextField!\n    private var fadeOutValue: NSTextField!\n'),
    ('    private var stopTimer: Timer?\n', '    private var stopTimer: Timer?\n    private var fadeTimer: Timer?\n'),
    ('        timeline.onEventBoundsChanged = { [weak self] i, start, end in self?.eventBoundsChanged(i, start: start, end: end) }\n', '        timeline.onEventBoundsChanged = { [weak self] i, start, end in self?.eventBoundsChanged(i, start: start, end: end) }\n        timeline.onPlayEvent = { [weak self] i in self?.playRegionOnly(i) }\n        timeline.onEventGainChanged = { [weak self] i, gain in self?.eventGainChanged(i, gain: gain) }\n'),
    ('        let rs = label("Repair Strength", size: 11); rs.frame = NSRect(x: 15, y: panelH - 178, width: 105, height: 18); p2.addSubview(rs)\n        repairSlider = NSSlider(value: 0.5, minValue: 0, maxValue: 1, target: nil, action: nil)\n        repairSlider.frame = NSRect(x: 119, y: panelH - 181, width: pw - 150, height: 22)\n        repairSlider.isEnabled = false\n        p2.addSubview(repairSlider)\n        let repairNote = label("TYPE TRIM applies to every event of the selected phoneme", size: 10, color: NSColor(hex: 0x667783))\n', '''        let fi = label("Fade In", size: 10); fi.frame = NSRect(x: 15, y: panelH - 178, width: 48, height: 18); p2.addSubview(fi)\n        fadeInSlider = NSSlider(value: 12, minValue: 0, maxValue: 120, target: self, action: #selector(fadeChanged))\n        fadeInSlider.frame = NSRect(x: 63, y: panelH - 181, width: 94, height: 22)\n        fadeInSlider.isEnabled = false\n        p2.addSubview(fadeInSlider)\n        fadeInValue = label("12 ms", size: 9, weight: .semibold, color: NSColor(hex: 0x9DB4C5))\n        fadeInValue.frame = NSRect(x: 158, y: panelH - 178, width: 42, height: 18)\n        p2.addSubview(fadeInValue)\n\n        let fo = label("Fade Out", size: 10); fo.frame = NSRect(x: 211, y: panelH - 178, width: 54, height: 18); p2.addSubview(fo)\n        fadeOutSlider = NSSlider(value: 12, minValue: 0, maxValue: 120, target: self, action: #selector(fadeChanged))\n        fadeOutSlider.frame = NSRect(x: 265, y: panelH - 181, width: max(70, pw - 330), height: 22)\n        fadeOutSlider.isEnabled = false\n        p2.addSubview(fadeOutSlider)\n        fadeOutValue = label("12 ms", size: 9, weight: .semibold, color: NSColor(hex: 0x9DB4C5))\n        fadeOutValue.frame = NSRect(x: pw - 55, y: panelH - 178, width: 42, height: 18)\n        p2.addSubview(fadeOutValue)\n\n        let repairNote = label("Click phoneme badge: play region only   •   mini fader: event gain", size: 10, color: NSColor(hex: 0x667783))\n'''),
    ('        typeTrimValue.stringValue = String(format: "%.1f dB", trim)\n        eventInfo.stringValue = String(format: "#%03d   [%@]   START %.3f s   END %.3f s   LEN %.0f ms   score %.2f   %@   trim %.1f dB", i + 1, e.kind, e.start, e.end, (e.end - e.start) * 1000, e.score, e.userLabel.isEmpty ? "UNRATED" : e.userLabel, trim)\n', '''        typeTrimValue.stringValue = String(format: "%.1f dB", trim)\n        fadeInSlider.isEnabled = true\n        fadeOutSlider.isEnabled = true\n        fadeInSlider.doubleValue = e.fadeIn * 1000\n        fadeOutSlider.doubleValue = e.fadeOut * 1000\n        fadeInValue.stringValue = String(format: "%.0f ms", e.fadeIn * 1000)\n        fadeOutValue.stringValue = String(format: "%.0f ms", e.fadeOut * 1000)\n        eventInfo.stringValue = String(format: "#%03d   [%@]   START %.3f s   END %.3f s   LEN %.0f ms   GAIN %.1f dB   IN %.0f ms   OUT %.0f ms   %@", i + 1, e.kind, e.start, e.end, (e.end - e.start) * 1000, e.gainDB, e.fadeIn * 1000, e.fadeOut * 1000, e.userLabel.isEmpty ? "UNRATED" : e.userLabel)\n'''),
    ('    @objc private func typeTrimChanged() {', '''    @objc private func fadeChanged() {\n        guard let i = timeline.selectedIndex, events.indices.contains(i) else { return }\n        let maxFade = max(0, (events[i].end - events[i].start) * 0.48)\n        events[i].fadeIn = min(fadeInSlider.doubleValue / 1000.0, maxFade)\n        events[i].fadeOut = min(fadeOutSlider.doubleValue / 1000.0, maxFade)\n        fadeInSlider.doubleValue = events[i].fadeIn * 1000\n        fadeOutSlider.doubleValue = events[i].fadeOut * 1000\n        timeline.events = events\n        selectEvent(i)\n        status.stringValue = String(format: "EVENT #%d CROSSFADES — IN %.0f ms / OUT %.0f ms", i + 1, events[i].fadeIn * 1000, events[i].fadeOut * 1000)\n    }\n\n    private func eventGainChanged(_ i: Int, gain: Double) {\n        guard events.indices.contains(i) else { return }\n        events[i].gainDB = min(0, max(-12, gain))\n        selectEvent(i)\n        status.stringValue = String(format: "EVENT #%d GAIN %.1f dB", i + 1, events[i].gainDB)\n    }\n\n    @objc private func typeTrimChanged() {'''),
    ('            typeTrimValue.stringValue = "0.0 dB"\n            eventInfo.stringValue = "No sibilance selected"\n', '            typeTrimValue.stringValue = "0.0 dB"\n            fadeInSlider.isEnabled = false\n            fadeOutSlider.isEnabled = false\n            eventInfo.stringValue = "No sibilance selected"\n'),
    ('    @objc private func playSelected() {', '''    private func playRegionOnly(_ i: Int) {\n        guard events.indices.contains(i), let url = model.url else { return }\n        if transportPlaying { stopTransport() }\n        previewPlayer?.stop()\n        stopTimer?.invalidate()\n        fadeTimer?.invalidate()\n        let e = events[i]\n        do {\n            let p = try AVAudioPlayer(contentsOf: url)\n            p.delegate = self\n            previewPlayer = p\n            let duration = max(0.02, e.end - e.start)\n            let targetVolume = Float(pow(10.0, e.gainDB / 20.0))\n            p.currentTime = e.start\n            p.volume = e.fadeIn > 0.001 ? 0 : targetVolume\n            p.play()\n            if e.fadeIn > 0.001 { p.setVolume(targetVolume, fadeDuration: e.fadeIn) }\n            let fadeOut = min(e.fadeOut, duration * 0.48)\n            if fadeOut > 0.001 {\n                fadeTimer = Timer.scheduledTimer(withTimeInterval: max(0.001, duration - fadeOut), repeats: false) { [weak self, weak p] _ in\n                    guard self?.previewPlayer === p else { return }\n                    p?.setVolume(0, fadeDuration: fadeOut)\n                }\n            }\n            stopTimer = Timer.scheduledTimer(withTimeInterval: duration, repeats: false) { [weak self, weak p] _ in\n                guard self?.previewPlayer === p else { return }\n                p?.stop()\n                self?.playButton.title = "▶ Play event"\n            }\n            timeline.playhead = e.start\n            playButton.title = "■ Stop"\n            status.stringValue = String(format: "REGION ONLY [%@]   %.3f–%.3f s   %.1f dB", e.kind, e.start, e.end, e.gainDB)\n        } catch {\n            status.stringValue = "REGION PLAYBACK FAILED"\n        }\n    }\n\n    @objc private func playSelected() {'''),
    ('        stopTimer?.invalidate()\n            let p = try AVAudioPlayer(contentsOf: url)', '        stopTimer?.invalidate()\n            fadeTimer?.invalidate()\n            let p = try AVAudioPlayer(contentsOf: url)'),
    ('        previewPlayer?.stop()\n        playButton.title = "▶ Play event"\n', '        previewPlayer?.stop()\n        fadeTimer?.invalidate()\n        playButton.title = "▶ Play event"\n')
]

for old, new in replacements:
    if old not in s:
        raise SystemExit(f'Missing expected snippet:\n{old[:240]}')
    s = s.replace(old, new, 1)

path.write_text(s)
