from pathlib import Path
p=Path('Sources/RGSibilanceStudio.swift')
s=p.read_text()
s=s.replace('let RGVersion = "0.2.20"','let RGVersion = "0.2.21"')
s=s.replace('    var onEventGainChanged: ((Int, Double) -> Void)?\n','    var onEventGainChanged: ((Int, Double) -> Void)?\n    var onEventFadesChanged: ((Int, Double, Double) -> Void)?\n')
s=s.replace('    private var gainDragIndex: Int?\n','    private var gainDragIndex: Int?\n    private var fadeDragIndex: Int?\n    private var fadeDragSide: Int = 0\n')
old='''        if let i = selectedIndex, events.indices.contains(i), gainFaderRect(for: i).contains(p) {\n            gainDragIndex = i\n            updateGainDrag(i, x: p.x)\n            return\n        }\n\n        if let i = selectedIndex, events.indices.contains(i) {'''
new='''        if let i = selectedIndex, events.indices.contains(i), gainFaderRect(for: i).contains(p) {\n            gainDragIndex = i\n            updateGainDrag(i, y: p.y)\n            return\n        }\n\n        if let i = selectedIndex, events.indices.contains(i) {\n            let e = events[i]\n            let inX = xForTime(min(e.end, e.start + e.fadeIn))\n            let outX = xForTime(max(e.start, e.end - e.fadeOut))\n            if abs(p.x - inX) <= 9 && abs(p.y - plotRect.midY) <= 42 {\n                fadeDragIndex = i\n                fadeDragSide = -1\n                return\n            }\n            if abs(p.x - outX) <= 9 && abs(p.y - plotRect.midY) <= 42 {\n                fadeDragIndex = i\n                fadeDragSide = 1\n                return\n            }\n        }\n\n        if let i = selectedIndex, events.indices.contains(i) {'''
assert old in s
s=s.replace(old,new)
old='''        if let i = gainDragIndex, events.indices.contains(i) {\n            updateGainDrag(i, x: p.x)\n        } else if boundaryDrag != 0,'''
new='''        if let i = gainDragIndex, events.indices.contains(i) {\n            updateGainDrag(i, y: p.y)\n        } else if let i = fadeDragIndex, events.indices.contains(i) {\n            updateFadeDrag(i, side: fadeDragSide, x: p.x)\n        } else if boundaryDrag != 0,'''
assert old in s
s=s.replace(old,new)
s=s.replace('        gainDragIndex = nil\n        needsDisplay = true\n','        gainDragIndex = nil\n        fadeDragIndex = nil\n        fadeDragSide = 0\n        needsDisplay = true\n')
old='''    private func gainFaderRect(for i: Int) -> NSRect {\n        guard events.indices.contains(i) else { return .zero }\n        let centerX = xForTime(events[i].peakTime)\n        return NSRect(x: centerX - 34, y: plotRect.maxY - 57, width: 68, height: 18)\n    }\n\n    private func updateGainDrag(_ i: Int, x: CGFloat) {\n        guard events.indices.contains(i) else { return }\n        let rect = gainFaderRect(for: i)\n        let fraction = min(1, max(0, (x - rect.minX) / max(1, rect.width)))\n        let value = -12.0 + Double(fraction) * 12.0\n        events[i].gainDB = value\n        onEventGainChanged?(i, value)\n        needsDisplay = true\n    }\n'''
new='''    private func gainFaderRect(for i: Int) -> NSRect {\n        guard events.indices.contains(i) else { return .zero }\n        let centerX = xForTime(events[i].peakTime)\n        return NSRect(x: centerX - 14, y: plotRect.midY - 76, width: 28, height: 152)\n    }\n\n    private func updateGainDrag(_ i: Int, y: CGFloat) {\n        guard events.indices.contains(i) else { return }\n        let range: CGFloat = 68\n        let clampedY = min(plotRect.midY + range, max(plotRect.midY - range, y))\n        let normalized = Double((clampedY - (plotRect.midY - range)) / (range * 2))\n        let value = -18.0 + normalized * 18.0\n        events[i].gainDB = min(0, max(-18, value))\n        onEventGainChanged?(i, events[i].gainDB)\n        needsDisplay = true\n    }\n\n    private func updateFadeDrag(_ i: Int, side: Int, x: CGFloat) {\n        guard events.indices.contains(i) else { return }\n        var e = events[i]\n        let t = timeForX(min(max(x, plotRect.minX), plotRect.maxX))\n        let maxFade = max(0, (e.end - e.start) * 0.48)\n        if side < 0 {\n            e.fadeIn = min(maxFade, max(0, t - e.start))\n        } else {\n            e.fadeOut = min(maxFade, max(0, e.end - t))\n        }\n        events[i] = e\n        onEventFadesChanged?(i, e.fadeIn, e.fadeOut)\n        needsDisplay = true\n    }\n\n    private func visualGain(at time: Double) -> Double {\n        guard let e = events.first(where: { time >= $0.start && time <= $0.end }) else { return 1.0 }\n        let target = pow(10.0, e.gainDB / 20.0)\n        if e.fadeIn > 0, time < e.start + e.fadeIn {\n            let x = min(1, max(0, (time - e.start) / e.fadeIn))\n            return 1.0 + (target - 1.0) * x\n        }\n        if e.fadeOut > 0, time > e.end - e.fadeOut {\n            let x = min(1, max(0, (e.end - time) / e.fadeOut))\n            return 1.0 + (target - 1.0) * x\n        }\n        return target\n    }\n'''
assert old in s
s=s.replace(old,new)
old='''            let x = plotRect.minX + CGFloat(column) / CGFloat(max(1, columns - 1)) * plotRect.width\n            path.move(to: NSPoint(x: x, y: plotRect.midY + CGFloat(mn) * plotRect.height * 0.48 * fixedVerticalScale))\n            path.line(to: NSPoint(x: x, y: plotRect.midY + CGFloat(mx) * plotRect.height * 0.48 * fixedVerticalScale))\n'''
new='''            let x = plotRect.minX + CGFloat(column) / CGFloat(max(1, columns - 1)) * plotRect.width\n            let time = viewStart + Double(column) / Double(max(1, columns - 1)) * visibleDuration\n            let gain = CGFloat(visualGain(at: time))\n            path.move(to: NSPoint(x: x, y: plotRect.midY + CGFloat(mn) * gain * plotRect.height * 0.48 * fixedVerticalScale))\n            path.line(to: NSPoint(x: x, y: plotRect.midY + CGFloat(mx) * gain * plotRect.height * 0.48 * fixedVerticalScale))\n'''
assert old in s
s=s.replace(old,new)
old='''            if selected {\n                let fader = gainFaderRect(for: i)\n                let lineY = fader.midY\n                let line = NSBezierPath()\n                line.move(to: NSPoint(x: fader.minX + 4, y: lineY))\n                line.line(to: NSPoint(x: fader.maxX - 4, y: lineY))\n                NSColor.white.withAlphaComponent(0.32).setStroke()\n                line.lineWidth = 2\n                line.stroke()\n                let norm = CGFloat((min(0, max(-12, e.gainDB)) + 12) / 12)\n                let knobX = fader.minX + 4 + norm * (fader.width - 8)\n                let knob = NSBezierPath(ovalIn: NSRect(x: knobX - 5, y: lineY - 5, width: 10, height: 10))\n                NSColor.white.setFill()\n                knob.fill()\n                let gattrs: [NSAttributedString.Key: Any] = [.font: NSFont.monospacedDigitSystemFont(ofSize: 8, weight: .semibold), .foregroundColor: NSColor.white.withAlphaComponent(0.85)]\n                String(format: "%.1f dB", e.gainDB).draw(at: NSPoint(x: fader.maxX + 4, y: fader.minY + 3), withAttributes: gattrs)\n            }\n'''
new='''            if selected {\n                let fader = gainFaderRect(for: i)\n                let centerX = fader.midX\n                let range: CGFloat = 68\n                let rail = NSBezierPath()\n                rail.move(to: NSPoint(x: centerX, y: plotRect.midY - range))\n                rail.line(to: NSPoint(x: centerX, y: plotRect.midY + range))\n                NSColor.white.withAlphaComponent(0.24).setStroke()\n                rail.lineWidth = 2\n                rail.stroke()\n                let norm = CGFloat((min(0, max(-18, e.gainDB)) + 18) / 18)\n                let knobY = plotRect.midY - range + norm * range * 2\n                let knob = NSBezierPath(roundedRect: NSRect(x: centerX - 9, y: knobY - 6, width: 18, height: 12), xRadius: 5, yRadius: 5)\n                NSColor.white.setFill()\n                knob.fill()\n                let gattrs: [NSAttributedString.Key: Any] = [.font: NSFont.monospacedDigitSystemFont(ofSize: 8, weight: .semibold), .foregroundColor: NSColor.white.withAlphaComponent(0.9)]\n                String(format: "%.1f", e.gainDB).draw(at: NSPoint(x: centerX + 13, y: knobY - 5), withAttributes: gattrs)\n\n                let inX = xForTime(min(e.end, e.start + e.fadeIn))\n                let outX = xForTime(max(e.start, e.end - e.fadeOut))\n                let fadeTop = plotRect.midY + 42\n                let fadeBottom = plotRect.midY - 42\n                let fadeInPath = NSBezierPath()\n                fadeInPath.move(to: NSPoint(x: startX, y: fadeTop))\n                fadeInPath.line(to: NSPoint(x: inX, y: fadeBottom))\n                color.withAlphaComponent(0.9).setStroke()\n                fadeInPath.lineWidth = 2\n                fadeInPath.stroke()\n                let fadeOutPath = NSBezierPath()\n                fadeOutPath.move(to: NSPoint(x: outX, y: fadeBottom))\n                fadeOutPath.line(to: NSPoint(x: endX, y: fadeTop))\n                fadeOutPath.lineWidth = 2\n                fadeOutPath.stroke()\n                for x in [inX, outX] {\n                    let h = NSBezierPath(ovalIn: NSRect(x: x - 6, y: plotRect.midY - 6, width: 12, height: 12))\n                    color.setFill()\n                    h.fill()\n                    NSColor.white.setStroke()\n                    h.lineWidth = 1\n                    h.stroke()\n                }\n                let fattrs: [NSAttributedString.Key: Any] = [.font: NSFont.monospacedDigitSystemFont(ofSize: 8, weight: .medium), .foregroundColor: NSColor.white.withAlphaComponent(0.72)]\n                String(format: "IN %.0f ms", e.fadeIn * 1000).draw(at: NSPoint(x: startX + 4, y: fadeTop + 5), withAttributes: fattrs)\n                String(format: "OUT %.0f ms", e.fadeOut * 1000).draw(at: NSPoint(x: max(startX, endX - 58), y: fadeTop + 5), withAttributes: fattrs)\n            }\n'''
assert old in s
s=s.replace(old,new)
s=s.replace('"Scroll: zoom   •   drag waveform: scrub   •   drag region edges: edit START/END   •   drag time ruler: move timeline   •   Space: play/stop"','"Scroll: zoom   •   center fader: event gain   •   fade dots: crossfade length   •   region edges: START/END   •   Space: play/stop"')
s=s.replace('        timeline.onEventGainChanged = { [weak self] i, gain in self?.eventGainChanged(i, gain: gain) }\n','        timeline.onEventGainChanged = { [weak self] i, gain in self?.eventGainChanged(i, gain: gain) }\n        timeline.onEventFadesChanged = { [weak self] i, fadeIn, fadeOut in self?.eventFadesChanged(i, fadeIn: fadeIn, fadeOut: fadeOut) }\n')
s=s.replace('events[i].gainDB = min(0, max(-12, gain))','events[i].gainDB = min(0, max(-18, gain))')
needle='''    @objc private func typeTrimChanged() {'''
insert='''    private func eventFadesChanged(_ i: Int, fadeIn: Double, fadeOut: Double) {\n        guard events.indices.contains(i) else { return }\n        events[i].fadeIn = fadeIn\n        events[i].fadeOut = fadeOut\n        fadeInSlider.doubleValue = fadeIn * 1000\n        fadeOutSlider.doubleValue = fadeOut * 1000\n        fadeInValue.stringValue = String(format: "%.0f ms", fadeIn * 1000)\n        fadeOutValue.stringValue = String(format: "%.0f ms", fadeOut * 1000)\n        timeline.events = events\n        selectEvent(i)\n        status.stringValue = String(format: "EVENT #%d CROSSFADES — IN %.0f ms / OUT %.0f ms", i + 1, fadeIn * 1000, fadeOut * 1000)\n    }\n\n'''+needle
assert needle in s
s=s.replace(needle,insert,1)
p.write_text(s)
print('patched 0.2.21')
