from pathlib import Path
p=Path('Sources/RGSibilanceStudio.swift')
s=p.read_text()
s=s.replace('let RGVersion = "0.2.30"','let RGVersion = "0.2.31"',1)
s=s.replace('    var userLabel: String\n    var gainDB: Double = 0','    var userLabel: String\n    var note: String? = nil\n    var gainDB: Double = 0',1)
s=s.replace('    private var detectedFooter: NSTextField!\n','    private var detectedFooter: NSTextField!\n    private var pinnedEventLabel: NSTextField!\n    private var pinnedGainSlider: NSSlider!\n    private var pinnedNoteLabel: NSTextField!\n',1)
# reserve a fixed inspector strip above the timeline
s=s.replace('timeline = TimelineView(frame: NSRect(x: 12, y: 48, width: editor.bounds.width - 66, height: editorH - 82))','timeline = TimelineView(frame: NSRect(x: 12, y: 48, width: editor.bounds.width - 66, height: editorH - 124))',1)
anchor='''        let timeHint = label("locator / selected event", size: 9, color: NSColor(hex: 0x637482))\n        timeHint.frame = NSRect(x: 166, y: editorH - 34, width: 150, height: 18)\n        editor.addSubview(timeHint)\n'''
insert=anchor+'''\n        // Pinned event inspector: stays available while the viewport/time position changes.\n        let pinned = makePanel(NSRect(x: 330, y: editorH - 48, width: editor.bounds.width - 396, height: 38))\n        pinned.fillColor = NSColor(hex: 0x0F1D28)\n        pinnedEventLabel = label("NO EVENT SELECTED", size: 10, weight: .bold, color: NSColor(hex: 0x8FA0AD))\n        pinnedEventLabel.frame = NSRect(x: 10, y: 10, width: 205, height: 18)\n        pinned.addSubview(pinnedEventLabel)\n        let pPlay = button("▶", action: #selector(playSelected)); pPlay.frame = NSRect(x: 218, y: 5, width: 34, height: 28); pinned.addSubview(pPlay)\n        let pGood = button("GOOD", action: #selector(markGood)); pGood.frame = NSRect(x: 256, y: 5, width: 55, height: 28); pinned.addSubview(pGood)\n        let pBad = button("BAD", action: #selector(markBad)); pBad.frame = NSRect(x: 315, y: 5, width: 50, height: 28); pinned.addSubview(pBad)\n        let pNote = button("✎ Note", action: #selector(addAnnotation)); pNote.frame = NSRect(x: 369, y: 5, width: 72, height: 28); pinned.addSubview(pNote)\n        pinnedGainSlider = NSSlider(value: 0, minValue: -18, maxValue: 0, target: self, action: #selector(pinnedGainChanged(_:)))\n        pinnedGainSlider.frame = NSRect(x: 448, y: 8, width: 128, height: 22); pinnedGainSlider.isEnabled = false; pinned.addSubview(pinnedGainSlider)\n        pinnedNoteLabel = label("", size: 9, color: NSColor(hex: 0x8FA0AD))\n        pinnedNoteLabel.frame = NSRect(x: 582, y: 10, width: max(80, pinned.bounds.width - 592), height: 18)\n        pinnedNoteLabel.lineBreakMode = .byTruncatingTail\n        pinned.addSubview(pinnedNoteLabel)\n        editor.addSubview(pinned)\n'''
if anchor not in s: raise SystemExit('timeHint anchor missing')
s=s.replace(anchor,insert,1)
# show annotation bubble on waveform
badge_anchor='''            badgeText.draw(at: NSPoint(x: centerX - textSize.width / 2, y: badgeY + (badgeH - textSize.height) / 2), withAttributes: attrs)\n\n            if selected {\n'''
badge_insert='''            badgeText.draw(at: NSPoint(x: centerX - textSize.width / 2, y: badgeY + (badgeH - textSize.height) / 2), withAttributes: attrs)\n\n            if let note = e.note, !note.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {\n                let bubbleText = "✎ " + note\n                let nattrs: [NSAttributedString.Key: Any] = [.font: NSFont.systemFont(ofSize: 9, weight: .medium), .foregroundColor: NSColor.white]\n                let ns = bubbleText.size(withAttributes: nattrs)\n                let bw = min(CGFloat(220), max(CGFloat(54), ns.width + 16))\n                let bx = min(plotRect.maxX - bw - 4, max(plotRect.minX + 4, centerX - bw / 2))\n                let by = badgeY - 25\n                let bubble = NSBezierPath(roundedRect: NSRect(x: bx, y: by, width: bw, height: 20), xRadius: 6, yRadius: 6)\n                NSColor(hex: 0x243A4A).withAlphaComponent(selected ? 0.98 : 0.78).setFill(); bubble.fill()\n                bubbleText.draw(in: NSRect(x: bx + 8, y: by + 4, width: bw - 16, height: 14), withAttributes: nattrs)\n            }\n\n            if selected {\n'''
if badge_anchor not in s: raise SystemExit('badge anchor missing')
s=s.replace(badge_anchor,badge_insert,1)
# update pinned controls on selection
select_anchor='''        autoRepairButton.isEnabled = true\n        applySimilarButton.isEnabled = true\n        eventInfo.stringValue = String(format: "#%03d [%@]  %.3f–%.3f s  %.0f ms  GAIN %.1f dB  IN %.0f / OUT %.0f ms  %@  •  %@", i + 1, e.kind, e.start, e.end, (e.end - e.start) * 1000, e.gainDB, e.fadeIn * 1000, e.fadeOut * 1000, e.userLabel.isEmpty ? "UNRATED" : e.userLabel, "METHOD \\(e.repairMethod ?? \"MANUAL\") • \\(RGRepairAdvisor.qualityText(for: e))")\n'''
select_insert='''        autoRepairButton.isEnabled = true\n        applySimilarButton.isEnabled = true\n        pinnedEventLabel?.stringValue = String(format: "#%03d  [%@]  %.3f–%.3f", i + 1, e.kind, e.start, e.end)\n        pinnedGainSlider?.isEnabled = true\n        pinnedGainSlider?.doubleValue = e.gainDB\n        pinnedNoteLabel?.stringValue = (e.note?.isEmpty == false) ? "✎ \\(e.note!)" : "No annotation"\n        eventInfo.stringValue = String(format: "#%03d [%@]  %.3f–%.3f s  %.0f ms  GAIN %.1f dB  IN %.0f / OUT %.0f ms  %@  •  %@", i + 1, e.kind, e.start, e.end, (e.end - e.start) * 1000, e.gainDB, e.fadeIn * 1000, e.fadeOut * 1000, e.userLabel.isEmpty ? "UNRATED" : e.userLabel, "METHOD \\(e.repairMethod ?? \"MANUAL\") • \\(RGRepairAdvisor.qualityText(for: e))")\n'''
if select_anchor not in s: raise SystemExit('select anchor missing')
s=s.replace(select_anchor,select_insert,1)
# add actions before eventBoundsChanged
method_anchor='''    private func eventBoundsChanged(_ i: Int, start: Double, end: Double) {\n'''
methods='''    @objc private func pinnedGainChanged(_ sender: NSSlider) {\n        guard let i = timeline.selectedIndex, events.indices.contains(i) else { return }\n        eventGainChanged(i, gain: sender.doubleValue)\n    }\n\n    @objc private func addAnnotation() {\n        guard let i = timeline.selectedIndex, events.indices.contains(i) else { status.stringValue = "SELECT AN EVENT FIRST"; return }\n        let alert = NSAlert()\n        alert.messageText = "Event annotation"\n        alert.informativeText = "Add a note to event #\\(i + 1) [\\(events[i].kind)]. It will stay attached to this event and appear on the waveform."\n        let field = NSTextField(frame: NSRect(x: 0, y: 0, width: 360, height: 24))\n        field.placeholderString = "e.g. too sharp, whistle, keep air, good reference…"\n        field.stringValue = events[i].note ?? ""\n        alert.accessoryView = field\n        alert.addButton(withTitle: "Save")\n        alert.addButton(withTitle: "Clear")\n        alert.addButton(withTitle: "Cancel")\n        let r = alert.runModal()\n        if r == .alertFirstButtonReturn {\n            let text = field.stringValue.trimmingCharacters(in: .whitespacesAndNewlines)\n            events[i].note = text.isEmpty ? nil : text\n        } else if r == .alertSecondButtonReturn {\n            events[i].note = nil\n        } else { return }\n        timeline.events = events\n        selectEvent(i)\n        saveCurrentSession()\n        status.stringValue = events[i].note == nil ? "ANNOTATION CLEARED" : "ANNOTATION SAVED — EVENT #\\(i + 1)"\n    }\n\n'''+method_anchor
if method_anchor not in s: raise SystemExit('method anchor missing')
s=s.replace(method_anchor,methods,1)
p.write_text(s)
print('patched 0.2.31')
